annotations:
  atalog.cattle.io/auto-install: opni-crd=match
  catalog.cattle.io/display-name: Opni
  catalog.cattle.io/os: linux
  catalog.rancher.io/namespace: opni-system
  catalog.rancher.io/release-name: opni
apiVersion: v2
appVersion: 0.4.0
description: Multi-cluster Monitoring and Logging System
icon: https://raw.githubusercontent.com/rancher/opni-docs/main/docs/assets/icon-opni.svg
keywords:
- opni
- monitoring
- logging
- rancher
- observability
kubeVersion: '>=1.22.0'
maintainers:
- email: joe.kralicky@suse.com
  name: Joe Kralicky
- email: dan.bason@suse.com
  name: Dan Bason
name: opni
type: application
version: 0.4.1
